import { useEffect, useState, type ReactNode } from "react";

// MermaidBlock renders a ```mermaid fence as a diagram (INC-51 余项).
//
// LAZY (the point of this file): mermaid is ~1.3 MB minified, so it must not
// ride the main bundle. The dynamic import below is Vite's code-split seam —
// the chunk downloads the first time a thread actually shows a mermaid block,
// never before. The promise is cached so N blocks share one load.
//
// SECURITY: the SVG below goes in via dangerouslySetInnerHTML, which is a
// deliberate, bounded exception to Markdown.tsx's no-raw-HTML red line. The
// markup is GENERATED by mermaid from diagram text (never author HTML passed
// through), and securityLevel "strict" keeps label HTML escaped and click
// directives dead. A render/parse failure — including a half-streamed fence —
// falls back to the plain CodeBlock; the thread never breaks on bad source.

let mermaidLoad: Promise<typeof import("mermaid")> | null = null;
const loadMermaid = () => (mermaidLoad ??= import("mermaid"));

let renderSeq = 0;

function prefersDark(): boolean {
  const forced = document.documentElement.getAttribute("data-theme");
  if (forced) return forced === "dark";
  return window.matchMedia?.("(prefers-color-scheme: dark)").matches ?? false;
}

export function MermaidBlock({ raw, fallback }: { raw: string; fallback: ReactNode }) {
  const [svg, setSvg] = useState<string | null>(null);
  useEffect(() => {
    let alive = true;
    setSvg(null);
    (async () => {
      try {
        const { default: mermaid } = await loadMermaid();
        mermaid.initialize({ startOnLoad: false, securityLevel: "strict", theme: prefersDark() ? "dark" : "default" });
        const { svg: rendered } = await mermaid.render(`ar-mmd-${++renderSeq}`, raw);
        if (alive) setSvg(rendered);
      } catch {
        /* fall through to the code-block fallback */
      }
    })();
    return () => {
      alive = false;
    };
  }, [raw]);
  // Loading and failure both show the source as a normal code block — honest,
  // and stable while an answer is still streaming the fence.
  if (svg === null) return <>{fallback}</>;
  return <div className="md-mermaid my-[2px] max-w-full overflow-x-auto" dangerouslySetInnerHTML={{ __html: svg }} />;
}
